// Begriffe erklärt (Wiki / Legende). Kurztext für Info-Buttons, Langtext für die Wiki-Seite.
import type { Lang } from "./types";

export type WikiCat = "belastung" | "erholung" | "planung" | "leistung" | "wachstum" | "gesundheit" | "app";
export interface WikiText { t: string; s: string; l: string[] }
export interface WikiEntry { k: string; cat: WikiCat; tags: string[]; de: WikiText; en: WikiText; src?: string }

export const WIKI_CATS: WikiCat[] = ["belastung", "erholung", "planung", "leistung", "wachstum", "gesundheit", "app"];

export const WIKI: WikiEntry[] = [
  // ---------------- Belastung ----------------
  { k: "rpe", cat: "belastung", tags: ["RPE", "Borg", "CR10", "Intensität"], src: "Foster et al. 2001",
    de: { t: "RPE (Anstrengungsempfinden)", s: "Wie anstrengend war die Einheit? Skala 0–10, etwa 30 Minuten nach dem Ende angegeben.",
      l: ["RPE (Rating of Perceived Exertion) ist das subjektive Anstrengungsempfinden auf der CR10-Skala: 0 = Ruhe, 3 = leicht, 5 = mittel/hart, 7 = sehr hart, 10 = maximal.",
        "Der Wert wird für die ganze Einheit angegeben, nicht für die härteste Übung – am besten 15–30 Minuten nach dem Ende, damit das letzte Spiel nicht alles überlagert.",
        "Ehrlich angeben ist wichtiger als „gut aussehen“: Nur echte Werte machen die Belastungssteuerung sinnvoll."] },
    en: { t: "RPE (rating of perceived exertion)", s: "How hard was the session? Scale 0–10, given about 30 minutes after the end.",
      l: ["RPE is the subjective effort on the CR10 scale: 0 = rest, 3 = easy, 5 = moderate/hard, 7 = very hard, 10 = maximal.",
        "Rate the whole session, not the hardest drill – ideally 15–30 minutes after the end so the final game does not dominate.",
        "Honest values matter more than looking good: only real values make load management meaningful."] } },
  { k: "au", cat: "belastung", tags: ["AU", "sRPE", "Session-RPE", "Last"], src: "Foster et al. 2001",
    de: { t: "Trainingslast (sRPE, AU)", s: "RPE × Minuten. Eine 90-Minuten-Einheit mit RPE 6 ergibt 540 AU (Arbitrary Units).",
      l: ["Die Session-RPE-Methode verbindet Intensität und Dauer: Last = RPE × Minuten, angegeben in AU (Arbitrary Units).",
        "Tageslast ist die Summe aller Einheiten eines Tages (inkl. Zusatzsport), Wochenlast die Summe von 7 Tagen.",
        "Die Methode ist im Fußball gut untersucht und braucht keine Technik – nur ehrliche Angaben."] },
    en: { t: "Training load (sRPE, AU)", s: "RPE × minutes. A 90-minute session at RPE 6 gives 540 AU (arbitrary units).",
      l: ["The session-RPE method combines intensity and duration: load = RPE × minutes, in AU (arbitrary units).",
        "Daily load is the sum of all sessions of a day (incl. extra sport), weekly load the sum of 7 days.",
        "The method is well studied in football and needs no equipment – just honest entries."] } },
  { k: "acwr", cat: "belastung", tags: ["ACWR", "akut", "chronisch", "Belastungsverhältnis", "Sweet Spot"], src: "Gabbett 2016; Lolli et al. 2019; Impellizzeri et al. 2020",
    de: { t: "ACWR (Belastungsverhältnis)", s: "Last der letzten 7 Tage geteilt durch die durchschnittliche Wochenlast der 3 Wochen davor. 0,8–1,3 = gewohnter Bereich.",
      l: ["ACWR (Acute:Chronic Workload Ratio) vergleicht die akute Belastung (letzte 7 Tage) mit der gewohnten Belastung (Wochenmittel der 3 Wochen davor). Trainerbank rechnet „entkoppelt“, d. h. die aktuelle Woche ist nicht in der gewohnten Belastung enthalten – das vermeidet eine bekannte Rechenverzerrung.",
        "Orientierung: unter 0,8 = weniger als gewohnt (Trainingsrückstand möglich), 0,8–1,3 = gewohnter Bereich, 1,3–1,5 = deutlich mehr (beobachten), über 1,5 = starker Sprung.",
        "Wichtig: Der ACWR ist kein Verletzungsprognose-Wert. Er zeigt nur, ob die Belastung plötzlich stark von der Gewohnheit abweicht. Zusammen mit Schlaf, Beschwerden und Gesprächen ergibt sich ein Bild.",
        "Aussagekräftig erst nach etwa 3–4 Wochen Daten; vorher zeigt die App „Aufbau“."] },
    en: { t: "ACWR (acute:chronic workload ratio)", s: "Load of the last 7 days divided by the average weekly load of the 3 weeks before. 0.8–1.3 = usual range.",
      l: ["ACWR compares the acute load (last 7 days) with the usual load (weekly mean of the 3 previous weeks). Trainerbank uses the uncoupled version: the current week is not part of the usual load, which avoids a known mathematical bias.",
        "Guide: below 0.8 = less than usual (possible fitness gap), 0.8–1.3 = usual range, 1.3–1.5 = clearly more (monitor), above 1.5 = big jump.",
        "Important: ACWR does not predict injuries. It only shows whether load suddenly deviates from what the player is used to. Combined with sleep, complaints and conversations it gives a picture.",
        "Meaningful after about 3–4 weeks of data; before that the app shows “build-up”."] } },
  { k: "mono", cat: "belastung", tags: ["Monotonie", "Strain", "Abwechslung"], src: "Foster 1998",
    de: { t: "Monotonie", s: "Wie gleichförmig die Woche war: mittlere Tageslast geteilt durch ihre Schwankung. Über 2 = wenig Abwechslung.",
      l: ["Monotonie = Mittelwert der Tageslasten ÷ Standardabweichung (7 Tage). Hohe Werte bedeuten: jeden Tag ähnlich hart, kaum leichte Tage.",
        "Abwechslung zwischen harten und leichten Tagen erleichtert Erholung. Werte über 2 sind ein Hinweis, Regenerationstage einzuplanen."] },
    en: { t: "Monotony", s: "How uniform the week was: mean daily load divided by its variation. Above 2 = little variation.",
      l: ["Monotony = mean of daily loads ÷ standard deviation (7 days). High values mean every day was similarly hard with hardly any easy days.",
        "Alternating hard and easy days supports recovery. Values above 2 suggest planning recovery days."] } },
  { k: "ampel", cat: "belastung", tags: ["Ampel", "Status", "kritisch", "erhöht", "im Plan", "niedrig", "Aufbau"],
    de: { t: "Ampel (Status)", s: "Rot = starker Belastungssprung, Orange = erhöht, Grün = im Plan, Blau = weniger als gewohnt, Grau = noch zu wenig Daten.",
      l: ["Die Ampel fasst Belastungsverhältnis, Erholung, Beschwerden und Abwesenheiten zusammen.",
        "Kritisch (rot): ACWR über 1,5 oder deutliche Beschwerden. Erhöht (orange): ACWR 1,3–1,5 oder Warnzeichen wie wenig Schlaf. Im Plan (grün): gewohnter Bereich. Niedrig (blau): ACWR unter 0,8. Aufbau (grau): weniger als 21 Tage Daten. Verletzt: aktuelle Verletzung oder Krankheit."] },
    en: { t: "Traffic light (status)", s: "Red = big load jump, orange = elevated, green = on track, blue = less than usual, grey = not enough data yet.",
      l: ["The traffic light combines load ratio, recovery, complaints and absences.",
        "Critical (red): ACWR above 1.5 or clear complaints. Elevated (orange): ACWR 1.3–1.5 or warning signs such as little sleep. On track (green): usual range. Low (blue): ACWR below 0.8. Build-up (grey): fewer than 21 days of data. Injured: current injury or illness."] } },
  // ---------------- Erholung ----------------
  { k: "recovery", cat: "erholung", tags: ["Erholung", "Erholungszeit", "bereit", "Readiness"], src: "Nédélec et al. 2012; Silva et al. 2018",
    de: { t: "Erholungszeit", s: "Wie lange der Körper nach harten Einheiten (RPE ≥ 7) oder Spielen braucht – abhängig von Alter, Schlaf, Beschwerden und Tests.",
      l: ["Nach intensiven Einheiten und Spielen sind Kraft, Sprintfähigkeit und Muskelschaden 48–72 Stunden beeinträchtigt; Jugendliche erholen sich meist schneller als Erwachsene.",
        "Trainerbank rechnet mit 9 Altersstufen und verlängert die Zeit bei wenig Schlaf, Beschwerden, deutlichem Abfall im Sprungtest (CMJ) oder geringer Fitness. Wer bei der nächsten harten Einheit noch nicht erholt ist, steht in der Planung als „nicht bereit“."] },
    en: { t: "Recovery time", s: "How long the body needs after hard sessions (RPE ≥ 7) or matches – depending on age, sleep, complaints and tests.",
      l: ["After intense sessions and matches, strength, sprint ability and muscle damage are affected for 48–72 hours; youth players usually recover faster than adults.",
        "Trainerbank uses 9 age bands and extends the time for little sleep, complaints, a clear drop in the jump test (CMJ) or low fitness. Players not recovered by the next hard session are marked “not ready” in planning."] } },
  { k: "hooper", cat: "erholung", tags: ["Morgen-Check", "Wellness", "Hooper", "Schlaf", "Müdigkeit", "Muskelkater", "Stress"], src: "Hooper & Mackinnon 1995",
    de: { t: "Morgen-Check (Hooper)", s: "Kurzer Fragebogen am Morgen: Schlafdauer, Schlafqualität, Müdigkeit, Muskelkater, Stress, Beschwerden.",
      l: ["Der Hooper-Index fragt vier Bereiche auf einer Skala ab (Schlafqualität, Müdigkeit, Muskelkater, Stress). Steigende Werte über mehrere Tage sind ein frühes Zeichen für zu wenig Erholung.",
        "Beschwerden werden mit Körperregion erfasst, damit Training und Tipps gezielt angepasst werden können (z. B. hintere Oberschenkel anders als Schulter)."] },
    en: { t: "Morning check (Hooper)", s: "Short morning questionnaire: sleep duration, sleep quality, fatigue, soreness, stress, complaints.",
      l: ["The Hooper index rates four areas (sleep quality, fatigue, muscle soreness, stress). Rising values over several days are an early sign of insufficient recovery.",
        "Complaints are recorded with body region so training and tips can be adapted specifically (e.g. hamstrings differently from shoulder)."] } },
  { k: "sleep", cat: "erholung", tags: ["Schlaf", "Sleep"], src: "Hirshkowitz et al. 2015 (National Sleep Foundation)",
    de: { t: "Schlaf", s: "Jugendliche (14–17) brauchen 8–10 Stunden, junge Erwachsene 7–9. Schlaf ist die wichtigste Erholungsmaßnahme.",
      l: ["Zu wenig Schlaf verringert Sprint- und Entscheidungsleistung und erhöht das Verletzungsrisiko bei Jugendlichen.",
        "Tipps: feste Zeiten, Handy 30–60 Minuten vor dem Schlafen weg, kühles dunkles Zimmer, nach Abendspielen bewusst runterfahren."] },
    en: { t: "Sleep", s: "Teenagers (14–17) need 8–10 hours, young adults 7–9. Sleep is the most important recovery tool.",
      l: ["Too little sleep reduces sprint and decision-making performance and raises injury risk in adolescents.",
        "Tips: fixed times, phone away 30–60 minutes before bed, cool dark room, wind down consciously after evening matches."] } },
  { k: "cmj_check", cat: "erholung", tags: ["CMJ", "Sprungtest", "Ermüdung", "neuromuskulär"], src: "Claudino et al. 2017",
    de: { t: "Sprungtest als Ermüdungscheck", s: "Fällt die Sprunghöhe (CMJ) um 5 % oder mehr unter den persönlichen Wert, ist der Körper noch müde.",
      l: ["Der Countermovement Jump reagiert empfindlich auf neuromuskuläre Ermüdung. Trainerbank vergleicht den aktuellen Wert mit dem Mittel der letzten Messungen.",
        "Abfall ab 5 %: Erholungszeit +12 Stunden; ab 8 %: +24 Stunden und Hinweis auf eine leichtere Belastung."] },
    en: { t: "Jump test as fatigue check", s: "If jump height (CMJ) drops 5 % or more below the personal value, the body is still fatigued.",
      l: ["The countermovement jump is sensitive to neuromuscular fatigue. Trainerbank compares the current value with the mean of recent tests.",
        "Drop of 5 % or more: recovery +12 hours; 8 % or more: +24 hours and a hint to train lighter."] } },
  // ---------------- Planung ----------------
  { k: "md", cat: "planung", tags: ["MD", "Spieltag", "MD-1", "MD+1", "Matchday"], src: "Akenhead et al. 2016; Martín-García et al. 2018",
    de: { t: "MD (Spieltag-Bezug)", s: "MD = Spieltag. MD-4 heißt vier Tage vor dem Spiel, MD+1 einen Tag danach.",
      l: ["Die Wochenplanung richtet sich nach dem Abstand zum Spiel: MD+1 Regeneration bzw. Spielersatz, MD-4 die intensivste Einheit (Kraft, große Räume), MD-3 Ausdauer/Spielformen, MD-2 Taktik bei mittlerer Intensität, MD-1 kurz und knackig (Schnelligkeit, Standards).",
        "So kommt die höchste Belastung früh in der Woche und die Spieler sind am Spieltag frisch."] },
    en: { t: "MD (match day reference)", s: "MD = match day. MD-4 means four days before the match, MD+1 the day after.",
      l: ["Weekly planning follows the distance to the match: MD+1 recovery or compensation, MD-4 the most intense session (strength, large spaces), MD-3 endurance/games, MD-2 tactics at medium intensity, MD-1 short and sharp (speed, set pieces).",
        "This puts the highest load early in the week so players are fresh on match day."] } },
  { k: "weekmode", cat: "planung", tags: ["Erhalt", "Aufbau", "Entlastung", "Wochenmodus", "Normal"],
    de: { t: "Wochenmodus: Erhalt, Aufbau, Entlastung", s: "Erhalt = gewohnte Saisonbelastung halten. Aufbau = ca. +10 %. Entlastung = ca. −30 %.",
      l: ["Erhalt (früher „Normal“): Die App gleicht die Woche an die gewohnte Belastung des Teams an (etwa 0,85–1,25 der üblichen Wochenlast).",
        "Aufbau: gezielte Steigerung um etwa 10 % – sinnvoll in der Vorbereitung oder nach spielfreien Phasen. Entlastung: etwa 30 % weniger, z. B. nach englischen Wochen, vor wichtigen Spielen oder als Deload-Woche."] },
    en: { t: "Week mode: maintain, build, deload", s: "Maintain = keep the usual in-season load. Build = about +10 %. Deload = about −30 %.",
      l: ["Maintain (formerly “normal”): the app aligns the week with the team's usual load (about 0.85–1.25 of the usual weekly load).",
        "Build: targeted increase of about 10 % – useful in pre-season or after match-free periods. Deload: about 30 % less, e.g. after congested weeks, before key matches or as a deload week."] } },
  { k: "indiv", cat: "planung", tags: ["Spielersatz", "individuell", "Vorgabe", "Regeneration", "Startelf"],
    de: { t: "Team-Vorgabe und individuelle Vorgabe", s: "Der Team-RPE beschreibt den Reiz der Einheit. Jeder Spieler bekommt daraus eine eigene Vorgabe.",
      l: ["Beispiel MD+1: Spieler mit viel Einsatzzeit (ab ca. 60 Minuten) regenerieren (RPE 2–3). Spieler mit wenig oder keiner Einsatzzeit bekommen Spielersatz (RPE 6–7), damit ihnen der Spielreiz nicht fehlt.",
        "Außerdem: Reha-Gruppe nach Rückkehrstufe, nicht erholte Spieler eine Stufe leichter, Spieler im Wachstumsschub mit weniger Sprung- und Sprintvolumen, Torhüter mit eigenem Profil."] },
    en: { t: "Team target and individual target", s: "The team RPE describes the session stimulus. Each player gets an individual target derived from it.",
      l: ["Example MD+1: players with a lot of minutes (from about 60) recover (RPE 2–3). Players with few or no minutes get compensation training (RPE 6–7) so they do not miss the match stimulus.",
        "Also: rehab group by return stage, players not yet recovered one level lighter, players in a growth spurt with less jumping and sprinting volume, goalkeepers with their own profile."] } },
  { k: "taper", cat: "planung", tags: ["Taper", "Tapering", "Deload", "3:1", "Vorbereitung"], src: "Mujika 2003; Bosquet et al. 2007",
    de: { t: "Aufbau, Entlastung und Tapering", s: "Belastung stufenweise steigern (≤ 10–15 % pro Woche), nach zwei Aufbauwochen entlasten, vor dem ersten Spiel Umfang senken und Intensität halten.",
      l: ["In der Vorbereitung startet die Einstiegswoche bei etwa 75 % einer normalen Saisonwoche. Danach steigt die Belastung um höchstens 10–15 % pro Woche; nach zwei Aufbauwochen folgt eine Entlastungswoche (3:1).",
        "Tapering: In der letzten Woche vor dem ersten Pflichtspiel den Umfang um etwa 20–40 % senken, die Intensität aber halten – so kommen die Spieler frisch und scharf ins Spiel."] },
    en: { t: "Build-up, deload and tapering", s: "Increase load gradually (≤ 10–15 % per week), deload after two build-up weeks, reduce volume but keep intensity before the first match.",
      l: ["In pre-season the entry week starts at about 75 % of a normal in-season week. Load then rises by at most 10–15 % per week; after two build-up weeks follows a deload week (3:1).",
        "Tapering: in the last week before the first competitive match reduce volume by about 20–40 % but keep intensity – players arrive fresh and sharp."] } },
  { k: "break", cat: "planung", tags: ["Pause", "Winterpause", "Sommerpause", "Detraining"], src: "Mujika & Padilla 2000; Bangsbo 2008",
    de: { t: "Längere Pausen", s: "Nach 2–4 Wochen ohne Training sinkt die Ausdauer spürbar. 2–3 kurze, intensive Einheiten pro Woche erhalten sie weitgehend.",
      l: ["Die ersten 1–2 Wochen einer langen Pause dienen der aktiven Erholung (andere Sportarten). Danach hält ein kurzes Programm mit Intervallen, Kraft und lockeren Läufen das Niveau. In der letzten Woche helfen Sprints, damit der Start in die Vorbereitung nicht aus dem Stand kommt."] },
    en: { t: "Longer breaks", s: "After 2–4 weeks without training endurance drops noticeably. 2–3 short, intense sessions per week largely preserve it.",
      l: ["The first 1–2 weeks of a long break are for active recovery (other sports). After that a short programme of intervals, strength and easy runs maintains the level. In the last week sprints help so pre-season does not start from zero."] } },
  // ---------------- Leistung ----------------
  { k: "sprint", cat: "leistung", tags: ["Sprint", "10 m", "30 m", "Schnelligkeit"],
    de: { t: "Sprint 10 m / 30 m", s: "10 m misst die Beschleunigung, 30 m die Schnelligkeit. Gemessen mit Lichtschranken, Bestwert aus 2–3 Versuchen.",
      l: ["Start 0,5 m hinter der ersten Schranke aus dem Stand, volle Pause (2–3 Minuten) zwischen den Läufen. Zeiten sind nur mit gleicher Messmethode vergleichbar."] },
    en: { t: "Sprint 10 m / 30 m", s: "10 m measures acceleration, 30 m speed. Timed with light gates, best of 2–3 trials.",
      l: ["Standing start 0.5 m behind the first gate, full rest (2–3 minutes) between runs. Times are only comparable with the same timing method."] } },
  { k: "cmj", cat: "leistung", tags: ["CMJ", "Sprung", "Countermovement Jump", "Sprungkraft"],
    de: { t: "CMJ (Countermovement Jump)", s: "Sprung aus dem Stand mit Ausholbewegung, Hände in den Hüften. Misst die Sprungkraft der Beine (cm).",
      l: ["Gemessen mit Sprungmatte, Kraftmessplatte oder geprüfter App. Bestwert aus 3 Versuchen. Regelmäßig gemessen dient er zusätzlich als Ermüdungscheck."] },
    en: { t: "CMJ (countermovement jump)", s: "Standing jump with counter-movement, hands on hips. Measures leg power (cm).",
      l: ["Measured with a jump mat, force plate or validated app. Best of 3 trials. Measured regularly it also serves as a fatigue check."] } },
  { k: "ift", cat: "leistung", tags: ["30-15", "IFT", "VIFT", "Intervall", "Ausdauer"], src: "Buchheit 2008",
    de: { t: "30-15 Intermittent Fitness Test (IFT)", s: "30 Sekunden laufen, 15 Sekunden gehen, Tempo steigt alle 45 Sekunden. Ergebnis: Endgeschwindigkeit VIFT in km/h.",
      l: ["Der Test bildet die wiederholten Richtungswechsel und Pausen im Fußball gut ab. Aus VIFT berechnet die App persönliche Laufstrecken für Intervalle: 15 Sekunden laufen / 15 Sekunden Pause bei 90–95 % VIFT.",
        "So trainieren alle Spieler mit der gleichen relativen Intensität – statt alle die gleiche Strecke."] },
    en: { t: "30-15 Intermittent Fitness Test (IFT)", s: "Run 30 seconds, walk 15 seconds, speed increases every 45 seconds. Result: final speed VIFT in km/h.",
      l: ["The test reflects repeated changes of direction and pauses in football well. From VIFT the app calculates personal running distances for intervals: 15 s run / 15 s rest at 90–95 % VIFT.",
        "This way all players train at the same relative intensity – instead of the same distance."] } },
  { k: "yoyo", cat: "leistung", tags: ["Yo-Yo", "IR1", "Ausdauer"], src: "Bangsbo et al. 2008",
    de: { t: "Yo-Yo Intermittent Recovery Test (Level 1)", s: "2 × 20 m Pendelläufe mit 10 Sekunden aktiver Pause, Tempo steigt. Ergebnis: gelaufene Meter.",
      l: ["Misst die Fähigkeit, intensive Läufe zu wiederholen. Gut für Vergleiche über die Saison; für Laufvorgaben ist der 30-15 IFT praktischer."] },
    en: { t: "Yo-Yo intermittent recovery test (level 1)", s: "2 × 20 m shuttles with 10 seconds of active rest, increasing speed. Result: metres run.",
      l: ["Measures the ability to repeat intense runs. Good for comparisons across the season; for running targets the 30-15 IFT is more practical."] } },
  { k: "agility", cat: "leistung", tags: ["505", "Richtungswechsel", "Agilität"],
    de: { t: "505-Test (Richtungswechsel)", s: "Zeit für 5 m hin, 180°-Wende, 5 m zurück. Misst die Richtungswechsel-Schnelligkeit.",
      l: ["Beide Seiten testen (Wende links/rechts). Deutliche Seitenunterschiede sind ein Hinweis für gezieltes Training."] },
    en: { t: "505 test (change of direction)", s: "Time for 5 m out, 180° turn, 5 m back. Measures change-of-direction speed.",
      l: ["Test both sides (turning left/right). Clear side differences suggest targeted training."] } },
  { k: "bands", cat: "leistung", tags: ["Normwerte", "Einordnung", "Bewertung", "Platzierung"],
    de: { t: "Einordnung und Platzierung", s: "Testwerte werden nach Altersgruppe eingeordnet: Top, gut, mittel, Basis. Platzierungen zeigen Spielern nur ihren Rang.",
      l: ["Die Orientierungswerte stammen aus Studien mit Nachwuchs- und Amateurspielern und dienen der groben Einordnung, nicht der Auswahl.",
        "In der Spieler-App sieht jeder nur eigene Werte; auf Wunsch des Trainers zusätzlich die eigene Platzierung im Team und den Teambestwert – nie die Werte anderer."] },
    en: { t: "Rating and ranking", s: "Test values are rated by age group: top, good, average, basic. Rankings only show players their own position.",
      l: ["The reference values come from studies with youth and amateur players and serve as a rough guide, not for selection.",
        "In the player app everyone sees only their own values; if the coach allows, also their rank in the team and the team best – never the values of others."] } },
  // ---------------- Wachstum ----------------
  { k: "phv", cat: "wachstum", tags: ["Wachstumsschub", "PHV", "Wachstum", "Reife"], src: "Lloyd & Oliver 2012; Van der Sluis et al. 2014",
    de: { t: "Wachstumsschub (PHV)", s: "Phase des schnellsten Körperwachstums (meist 12–15 Jahre). Ab etwa 7 cm pro Jahr zeigt die App den Hinweis „Wachstumsschub“.",
      l: ["Im Wachstumsschub wachsen Knochen schneller als Muskeln und Sehnen. Das Risiko für Überlastungsbeschwerden an Knie (Osgood-Schlatter), Ferse (Sever) und Rücken steigt, die Koordination ist vorübergehend schlechter.",
        "Empfehlung: Sprung- und Sprintvolumen sowie harte Untergründe reduzieren, Technik und Beweglichkeit betonen, Beschwerden ernst nehmen. Körpergröße alle 3 Monate messen."] },
    en: { t: "Growth spurt (PHV)", s: "Phase of fastest growth (usually 12–15 years). From about 7 cm per year the app shows the “growth spurt” hint.",
      l: ["During the growth spurt bones grow faster than muscles and tendons. The risk of overuse complaints at the knee (Osgood-Schlatter), heel (Sever) and back rises, and coordination is temporarily worse.",
        "Recommendation: reduce jumping and sprinting volume and hard surfaces, emphasise technique and mobility, take complaints seriously. Measure height every 3 months."] } },
  // ---------------- Gesundheit ----------------
  { k: "rtp", cat: "gesundheit", tags: ["Rückkehr", "Reha", "Stufe", "Return to Play"], src: "Ardern et al. 2016",
    de: { t: "Rückkehr in 4 Stufen", s: "1 Reha/individuell, 2 Teiltraining, 3 volles Training, 4 spielfähig. Die Stufe setzt das Trainerteam nach Freigabe.",
      l: ["Stufe 1: individuelles Training bzw. Reha, kein Mannschaftstraining. Stufe 2: Teile des Trainings ohne Zweikämpfe und maximale Sprints. Stufe 3: volles Training. Stufe 4: spielfähig, Einsatzzeit langsam steigern.",
        "Über die Rückkehr entscheidet das medizinische Personal; die App unterstützt nur Planung und Übersicht."] },
    en: { t: "Return in 4 stages", s: "1 rehab/individual, 2 partial training, 3 full training, 4 match fit. The staff sets the stage after clearance.",
      l: ["Stage 1: individual training or rehab, no team training. Stage 2: parts of training without duels and maximal sprints. Stage 3: full training. Stage 4: match fit, increase playing time gradually.",
        "Medical staff decide on the return; the app only supports planning and overview."] } },
  { k: "complaints", cat: "gesundheit", tags: ["Beschwerden", "Schmerzen", "Neck-Check", "Erkältung", "Gehirnerschütterung", "Zerrung"], src: "Schwellnus et al. 2016; Patricios et al. 2023; Ekstrand et al. 2011",
    de: { t: "Beschwerden und Körperregionen", s: "Im Morgen-Check tippen Spieler an, wo es zwickt. Die Region bestimmt, was heute geht: Muskel, Gelenk, Sehne, Knochen, Rücken, Arm oder Krankheit wirken unterschiedlich.",
      l: ["Leichte Beschwerden: mitmachen, aber eine Stufe leichter bzw. ohne die belastende Bewegung (z. B. Wade: keine Maximalsprints; Schulter: keine Stürze; Nacken: keine Kopfbälle). Deutliche Beschwerden an Muskel, Gelenk, Sehne oder Knochen: kein Mannschaftstraining, Physio draufschauen lassen.",
        "Neck-Check bei Infekten: Nur Symptome oberhalb des Halses (Schnupfen, Halsweh) – lockeres Training geht. Fieber, Gliederschmerzen, Husten oder Magen-Darm: kein Sport, weil Belastung mit Fieber den Herzmuskel schädigen kann.",
        "Kopf: Nach einem Kopfstoß mit Schwindel, Übelkeit, Kopfschmerz oder Sehstörungen gilt Verdacht auf Gehirnerschütterung – am selben Tag kein Sport, ärztlich abklären, dann stufenweise zurück.",
        "Torhüter mit Arm- oder Schulterbeschwerden bekommen eigene Hinweise (kein Hechten auf die betroffene Seite)."] },
    en: { t: "Complaints and body regions", s: "In the morning check players tap where it hurts. The region decides what is possible today: muscle, joint, tendon, bone, back, arm or illness act differently.",
      l: ["Slight complaints: join in, but one level easier or without the loading movement (e.g. calf: no maximal sprints; shoulder: no falls; neck: no headers). Clear complaints of muscle, joint, tendon or bone: no team training, let the physio check.",
        "Neck check for infections: symptoms only above the neck (runny nose, sore throat) – easy training is fine. Fever, aching limbs, cough or stomach bug: no sport, because exercise with fever can damage the heart muscle.",
        "Head: after a blow to the head with dizziness, nausea, headache or vision problems, suspect concussion – no sport on the same day, see a doctor, then return step by step.",
        "Goalkeepers with arm or shoulder complaints get their own advice (no diving to the affected side)."] } },
  { k: "prevention", cat: "gesundheit", tags: ["Prävention", "Nordic", "Copenhagen", "FIFA 11+"], src: "van der Horst et al. 2015; Harøy et al. 2019; Thorborg et al. 2017",
    de: { t: "Verletzungsprävention", s: "Nordic Hamstrings, Copenhagen-Übung und das FIFA 11+-Aufwärmen senken das Risiko für typische Fußballverletzungen deutlich.",
      l: ["Nordic Hamstrings (2× pro Woche) reduzieren Verletzungen der hinteren Oberschenkel, die Copenhagen-Übung Leistenprobleme, das FIFA 11+-Programm Verletzungen insgesamt – wenn es regelmäßig gemacht wird."] },
    en: { t: "Injury prevention", s: "Nordic hamstrings, the Copenhagen exercise and the FIFA 11+ warm-up clearly reduce typical football injuries.",
      l: ["Nordic hamstrings (2× per week) reduce hamstring injuries, the Copenhagen exercise groin problems, the FIFA 11+ programme injuries overall – when done regularly."] } },
  // ---------------- App ----------------
  { k: "modules", cat: "app", tags: ["Module", "Baukasten", "Pakete", "Stufe"],
    de: { t: "Module und Stufen", s: "Organisation, Kompakt und Volle Tiefe sind Vorauswahlen. Jedes Modul lässt sich einzeln unter Mehr → Baukasten schalten.",
      l: ["Organisation: Kalender, Kader, Anwesenheit, Termine. Kompakt: dazu Wochenplanung, Belastung mit Ampel und Empfehlungen in Klartext. Volle Tiefe: alle Kennzahlen, Erholungsrechnung, Leistungsdiagnostik und Begründungen."] },
    en: { t: "Modules and levels", s: "Organisation, compact and full depth are presets. Each module can be switched under More → Modules.",
      l: ["Organisation: calendar, squad, attendance, events. Compact: plus weekly planning, load with traffic light and plain-language recommendations. Full depth: all metrics, recovery model, performance testing and explanations."] } },
  { k: "groups", cat: "app", tags: ["Gruppen", "Reha-Gruppe", "Torhüter"],
    de: { t: "Gruppen", s: "Spieler lassen sich Gruppen zuordnen (z. B. Reha, Torhüter, Wachstumsschub). Manche Gruppen verändern die Steuerung.",
      l: ["Gruppen mit Wirkung: Reha (individuelle Vorgabe nach Rückkehrstufe), Torhüter (eigenes Belastungsprofil), Wachstumsschub (weniger Sprung- und Sprintvolumen), Aufbau (vorsichtige Steigerung). Andere Gruppen dienen der Organisation, z. B. Kapitänsrat.",
        "Der Trainer entscheidet je Gruppe, ob Spieler ihre Zugehörigkeit sehen. Videos, Nachrichten und Aufgaben lassen sich an ganze Gruppen schicken."] },
    en: { t: "Groups", s: "Players can be assigned to groups (e.g. rehab, goalkeepers, growth spurt). Some groups change the steering.",
      l: ["Groups with effect: rehab (individual target by return stage), goalkeepers (own load profile), growth spurt (less jumping and sprinting), build-up (careful increase). Other groups are organisational, e.g. captains' council.",
        "The coach decides per group whether players see their membership. Videos, messages and tasks can be sent to whole groups."] } },
  { k: "duties", cat: "app", tags: ["Dienste", "Aufgaben", "Strafen", "Strafenkatalog", "Materialdienst"],
    de: { t: "Aufgaben, Dienste und Strafen", s: "Aufgaben für Trainer und Spieler, Dienste wie Materialdienst, ein anpassbarer Strafenkatalog mit automatischen Regeln.",
      l: ["Dienste wechseln reihum. Regeln können Strafen automatisch vergeben, z. B. „RPE nicht innerhalb von 24 Stunden eingetragen → Materialdienst beim nächsten Training“.",
        "Hinweis: RPE und Morgen-Check sind Gesundheitsdaten mit freiwilliger Einwilligung. Strafen sollten mild sein (Dienst statt Geld), nur für Spieler mit Einwilligung gelten und vorher im Team besprochen werden – sonst leidet die Ehrlichkeit der Angaben."] },
    en: { t: "Tasks, duties and fines", s: "Tasks for coaches and players, duties such as kit duty, a customisable fines catalogue with automatic rules.",
      l: ["Duties rotate. Rules can assign fines automatically, e.g. “RPE not entered within 24 hours → kit duty at the next session”.",
        "Note: RPE and the morning check are health data based on voluntary consent. Fines should be mild (duty instead of money), only apply to players who consented and be agreed in the team beforehand – otherwise the honesty of entries suffers."] } },
];

export const wikiText = (e: WikiEntry, lang: Lang): WikiText => lang === "en" ? e.en : e.de;
export const wikiOf = (k: string): WikiEntry | null => WIKI.find(x => x.k === k) || null;

/** Volltextsuche über Titel, Kurztext, Langtext und Stichwörter. */
export function searchWiki(q: string, lang: Lang): WikiEntry[] {
  const n = q.trim().toLowerCase(); if (!n) return WIKI;
  return WIKI.filter(e => { const x = wikiText(e, lang); return [x.t, x.s, ...x.l, ...e.tags].some(s => s.toLowerCase().includes(n)); });
}
